[package]
name = "somatize-core"
version.workspace = true
edition.workspace = true
readme = "../README.md"
license.workspace = true
repository.workspace = true
description = "Core types and traits for the Soma computational graph runtime"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
blake3 = { workspace = true }
ciborium = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
somatize-macros = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
