"""Replacing a generated tree, on a filesystem where deleting is not immediate.

Both generators here render a directory from a source that is the truth, so the
obvious shape is `rmtree` then write. It is wrong on this repository. The tree
lives on NFS, where deleting a file that anything still holds is a **rename** to
`.nfsXXXX`, so the `rmdir` that ends an `rmtree` intermittently fails with
`ENOTEMPTY` — measured here, one run in a handful — and leaves the directory
half-emptied with the script dead before it wrote anything back.

That failure is worse than it sounds, and it is worse for exactly one group. A
hand-listed group loses a page and `check-sidebar` fails on the dangling slug.
The **autogenerated** group has no such list, which is the whole point of
relaxing the guard for it — so it came back three pages short, built clean and
said nothing.

So: write first, prune afterwards, and then check. A crash now leaves stale
pages rather than missing ones, and a stale page is something a guard can see.
"""

from __future__ import annotations

from pathlib import Path


def rewrite(root: Path, files: dict[str, str | bytes]) -> None:
    """Make `root` hold exactly `files`, keyed by path relative to it."""
    root.mkdir(parents=True, exist_ok=True)
    for name, body in files.items():
        at = root / name
        at.parent.mkdir(parents=True, exist_ok=True)
        at.write_bytes(body) if isinstance(body, bytes) else at.write_text(body)

    wanted = {root / name for name in files}
    for found in sorted(root.rglob("*"), key=lambda p: -len(p.parts)):
        if found.is_dir():
            # Only if it emptied out. A directory that did not is either wanted
            # or an `.nfsXXXX` still standing, and neither is ours to force.
            if not any(found.iterdir()):
                found.rmdir()
        elif found not in wanted and not found.name.startswith(".nfs"):
            found.unlink()

    # The check the relaxed guard cannot do. Silence is what this exists to
    # prevent, so a tree that did not come out right stops the build here,
    # where the reason is still on screen.
    landed = {p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file()}
    missing = set(files) - landed
    if missing:
        raise SystemExit(f"{root}: {len(missing)} file(s) did not land: {sorted(missing)[:5]}")
