[package]
name = "somatize-macros"
version.workspace = true
edition.workspace = true
readme = "../README.md"
license.workspace = true
repository.workspace = true
description = "Derive macros for the Soma computational graph runtime"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
