[package]
name = "soma-python"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Python bindings for the Soma computational graph runtime"

[lib]
name = "_soma"
crate-type = ["cdylib"]

[dependencies]
soma-core = { version = "0.2.5", path = "../soma-core" }
soma-compiler = { version = "0.2.5", path = "../soma-compiler" }
soma-runtime = { version = "0.2.5", path = "../soma-runtime" }
pyo3 = { workspace = true }
numpy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
reqwest = { version = "0.12", features = ["json", "blocking"] }
